services:
  media-server-utility:
    image: ${DOCKERHUB_USER:-iplaza3d}/media-server-utility:latest
    container_name: media-server-utility
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./data:/data
      # Tus bibliotecas del NAS (lectura y escritura, necesario para renombrar). Ajusta la ruta del volumen
      - /volume1/video:/media
    ports: ["8080:8080"]
    restart: unless-stopped
