services:
  allarr:
    image: ${DOCKERHUB_USER:-iplaza3d}/allarr:latest
    container_name: allarr
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./data:/data
      # Tus bibliotecas del NAS (solo lectura). Ajusta la ruta del volumen
      - /volume1/video:/media:ro
    ports: ["8080:8080"]
    restart: unless-stopped
